apiVersion: v1
kind: Service
metadata:
  name: {{ include "sshark.fullname" . }}-api
  labels:
    {{- include "sshark.labels" . | nindent 4 }}
spec:
  type: ExternalName
  externalName: {{ .Values.api.name }}.{{ .Values.api.namespace }}.svc.cluster.local
  ports:
    - port: {{ .Values.api.port }}
      protocol: TCP
      name: http
